name: WauzCore
description: Advanced Minecraft MMORPG Engine - Main Module
main: eu.wauz.wauzcore.WauzCore
website: http://wauz.eu/
version: Behelit.12-SNAPSHOT
api-version: 1.16
author: Nikolas Keller
depend: [MythicMobs]
softdepend: [NoteBlockAPI]
commands:
  hub:
    description: Teleport to Hub
    usage: /hub
    permission: wauz.normal
  spawn:
    description: Teleport to Spawn
    usage: /spawn
    permission: wauz.normal
  home:
    description: Teleport to Home
    usage: /home
    permission: wauz.normal
  sethome:
    description: Set Home Location
    usage: /sethome
    permission: wauz.normal
  menu:
    description: Open a Menu
    usage: /menu [name]
    permission: wauz.normal
  group:
    description: Open the Group Menu
    usage: /group
    permission: wauz.normal
  grp:
    description: Send Message in Group Chat
    usage: /grp [text]
    permission: wauz.normal
  desc:
    description: Set the Group Description
    usage: /desc [text]
    permission: wauz.normal
  guild:
    description: Create a Guild
    usage: /guild [guildName]
    permission: wauz.normal
  apply:
    description: Apply for a Guild
    usage: /apply [guildName]
    permission: wauz.normal
  gld:
    description: Send Message in Guild Chat
    usage: /gld [text]
    permission: wauz.normal
  motd:
    description: Set the Guild Message of the Day
    usage: /modt [text]
    permission: wauz.normal
  item:
    description: Send Item in Chat
    usage: /item
    permission: wauz.normal
  rename:
    description: Rename Pet
    usage: /rename [name]
    permission: wauz.normal
  where:
    description: Get the Location of a Player
    usage: /where [player]
    permission: wauz.normal
  friend:
    description: Send a Friend Request to a Player
    usage: /friend [player]
    permission: wauz.normal
  trade:
    description: Send a Trade Request to a Player
    usage: /trade [player]
    permission: wauz.normal
  send:
    description: Send a Text Mail to a Player
    usage: /send [player] [text]
    permission: wauz.normal
  send.item:
    description: Send your Hand Item to a Player
    usage: /send.item [player] [text]
    permission: wauz.normal
  send.coins:
    description: Send Coins to a Player
    aliases: [pay]
    usage: /send.coins [player] [amount] [text]
    permission: wauz.normal
  leave:
    description: Leave Instance
    usage: /leave
    permission: wauz.normal
  sit:
    description: Sit Down
    usage: /sit
    permission: wauz.normal
  roll:
    description: Roll a Random Number
    usage: /roll [maximum]
    permission: wauz.normal
  tip:
    description: Print a Tip in Chat
    usage: /tip
    permission: wauz.normal
  talk:
    description: Talk to Nearest Citizen
    usage: /talk
    permission: wauz.normal
  start:
    description: Start Next Arcade Game
    usage: /start
    permission: wauz.normal
  nextwave:
    description: Start Next 5 Arena Waves
    usage: /nextwave
    permission: wauz.normal
  wzSystem:
    description: Print System Analytics
    usage: /wzSystem
    permission: wauz.system
  wzHeal:
    description: Heal and Feed Player
    aliases: [heal, feed]
    usage: /wzHeal [player]
    permission: wauz.system
  wzRepair:
    description: Repair Equipment of Player
    aliases: [repair]
    usage: /wzRepair [player]
    permission: wauz.system
  wzExp:
    description: Gain Experience Points
    usage: /wzExp [player] [tier] [amount]
    permission: wauz.system
  wzGamemode:
    description: Toggle Creative Mode
    aliases: [gm]
    usage: /wzGamemode [player]
    permission: wauz.system
  wzNightvision:
    description: Toggle Night Vision
    aliases: [nightvision]
    usage: /wzNightvision [player]
    permission: wauz.system
  wzEnter.dev:
    description: Enter Dev Instance
    usage: /wzEnter.dev [instance]
    permission: wauz.system
  wzEnter:
    description: Enter Instance
    usage: /wzEnter [instance]
    permission: wauz.system
  wzKey:
    description: Change Dungeon Key Status
    usage: /wzKey [world (this)] [keyId] [status (0, 1, 2)]
    permission: wauz.system
  wzEnd:
    description: End Arcade Game
    aliases: [end]
    usage: /wzEnd
    permission: wauz.system
  wzTravel:
    description: Travel to Location
    aliases: [warp]
    usage: /wzTravel [waypoint]
    permission: wauz.system
  wzTravelEvent:
    description: Event-Travel to Location per UUID
    usage: /wzTravelEvent [uuid]
    permission: wauz.normal
  wzSpeed.walking:
    description: Change Walking Speed
    aliases: [wspeed]
    usage: /wzSpeed.walking [speed (1-10)] [player]
    permission: wauz.system
  wzSpeed.flying:
    description: Change Flying Speed
    aliases: [fspeed]
    usage: /wzSpeed.flying [speed (1-10)] [player]
    permission: wauz.system
  wzRank:
    description: Change Rank of a Player
    usage: /wzRank [rank] [player]
    permission: wauz.system
  wzPerms:
    description: Show Permissions
    usage: /wzPerms [filter]
    permission: wauz.system
  wzFirework:
    description: Create Firework Show
    aliases: [firework]
    usage: /wzFirework
    permission: wauz.system
  wzDebug:
    description: Toggle Debug Mode
    usage: /wzDebug [player]
    permission: wauz.system
  wzDebug.magic:
    description: Toggle Magic Debug Mode
    usage: /wzDebug.magic [player]
    permission: wauz.system
  wzDebug.crafting:
    description: Toggle Crafting Debug Mode
    usage: /wzDebug.crafting [player]
    permission: wauz.system
  wzDebug.building:
    description: Toggle Building Debug Mode
    aliases: [build]
    usage: /wzDebug.building [player]
    permission: wauz.system
  wzDebug.flying:
    description: Toggle Flying Debug Mode
    aliases: [fly]
    usage: /wzDebug.flying [player]
    permission: wauz.system
  wzDebug.attack:
    description: Toggle Attack Debug Mode
    usage: /wzDebug.attack [player]
    permission: wauz.system
  wzDebug.defense:
    description: Toggle Defense Debug Mode
    usage: /wzDebug.defense [player]
    permission: wauz.system
  wzPetAbility:
    description: Force Pet to Use Ability
    aliases: [petability]
    usage: /wzPetAbility
    permission: wauz.system
  wzGetPet:
    description: Get Pet from String
    aliases: [getpet]
    usage: /wzGetPet [petname] [player]
    permission: wauz.system
  wzGetPet.ability:
    description: Get Ability Pet from String
    aliases: [getpet.ability]
    usage: /wzGetPet.ability [petname] [ability] [player]
    permission: wauz.system
  wzGetEquip:
    description: Get Equip from String
    aliases: [getequip]
    usage: /wzGetEquip [equipname] [tier] [player]
    permission: wauz.system
  wzGetEquip.enhanced:
    description: Get Enhanced Equip from String
    aliases: [getequip.enhanced]
    usage: /wzGetEquip.enhanced [enname] [enlvl] [player]
    permission: wauz.system
  wzGetRune:
    description: Get Rune from String
    aliases: [getrune]
    usage: /wzGetRune [runename] [player]
    permission: wauz.system
  wzSkill:
    description: Execute Skill
    usage: /wzSkill [skillname]
    permission: wauz.system
  wzSkill.weapon:
    description: Get Weapon with Skillgem
    usage: /wzSkill.weapon [skillname]
    permission: wauz.system
  wzStart:
    description: Start Specific Arcade Game
    usage: /wzStart [gamename]
    permission: wauz.system
permissions:
  wauz.system:
    description: Gives access to system commands.
    default: op
  wauz.normal:
    description: Permission assigned to new players.
    default: true
  wauz.debug:
    description: Shows the personalized debug log in chat.
    default: false
  wauz.debug.magic:
    description: Infinite mana and 1 second skill cooldowns.
    default: false
  wauz.debug.crafting:
    description: Unlock all recipes, craftable without cost.
    default: false
  wauz.debug.building:
    description: Enables building in all areas.
    default: false
  wauz.debug.flying:
    description: Allows to fly very fast in all modes.
    default: false
  wauz.debug.attack:
    description: Increases damage output drastically.
    default: false
  wauz.debug.defense:
    description: Reduces damage taken to zero.
    default: false