name: WauzCore
description: Advanced Minecraft MMORPG Engine - Main Module
main: eu.wauz.wauzcore.WauzCore
website: http://wauz.eu/
version: Behelit.1.Pre
api-version: 1.14
author: Nikolas Keller
depend: [MythicMobs, NoteBlockAPI]
commands:
  hub:
    description: Teleport to Hub
    usage: /hub
    permission: wauz.normal
  spawn:
    description: Teleport to Spawn
    usage: /spawn
    permission: wauz.normal
  home:
    description: Teleport to Home
    usage: /home
    permission: wauz.normal
  sethome:
    description: Set Home Location
    usage: /sethome
    permission: wauz.normal
  menu:
    description: Open a Menu
    usage: /menu [name]
    permission: wauz.normal
  group:
    description: Open the Group Menu
    usage: /group
    permission: wauz.normal
  grp:
    description: Send Message in Group Chat
    usage: /grp [text]
    permission: wauz.normal
  desc:
    description: Set the Group Description
    usage: /desc [text]
    permission: wauz.normal
  guild:
    description: Create a Guild
    usage: /guild [guildName]
    permission: wauz.normal
  apply:
    description: Apply for a Guild
    usage: /apply [guildName]
    permission: wauz.normal
  gld:
    description: Send Message in Guild Chat
    usage: /gld [text]
    permission: wauz.normal
  motd:
    description: Set the Guild Message of the Day
    usage: /modt [text]
    permission: wauz.normal
  tip:
    description: Print a Tip in Chat
    usage: /tip
    permission: wauz.normal
  wzSystem:
    description: Print System Analytics
    usage: /wzSystem
    permission: wauz.system
  wzHeal:
    description: Heal and Feed Player
    usage: /wzHeal [player]
    permission: wauz.system
  wzRepair:
    description: Repair Equipment of Player
    usage: /wzRepair [player]
    permission: wauz.system
  wzExp:
    description: Gain Experience Points
    usage: /wzExp [player] [tier] [amount]
    permission: wauz.system
  wzEnter.dev:
    description: Enter Dev Instance
    usage: /wzEnter.dev [instance]
    permission: wauz.system
  wzEnter:
    description: Enter Instance
    usage: /wzEnter [instance]
    permission: wauz.system
  wzLeave:
    description: Leave Instance
    usage: /wzLeave
    permission: wauz.system
  wzKey:
    description: Change Dungeon Key Status
    usage: /wzKey [world (this)] [keyId] [status (0, 1, 2)]
    permission: wauz.system
  wzTravel:
    description: Phantom-Travel to Location
    usage: /wzTravel [x, y, z]
    permission: wauz.system
  wzTravelEvent:
    description: Event-Travel to Location per UUID
    usage: /wzTravelEvent [uuid]
    permission: wauz.normal
  wzDebug:
    description: Toggle Debug Mode
    usage: /wzDebug [player]
    permission: wauz.system
  wzDebug.magic:
    description: Toggle Magic Debug Mode
    usage: /wzDebug.magic [player]
    permission: wauz.system
  wzDebug.crafting:
    description: Toggle Crafting Debug Mode
    usage: /wzDebug.crafting [player]
    permission: wauz.system
  wzDebug.building:
    description: Toggle Building Debug Mode
    usage: /wzDebug.building [player]
    permission: wauz.system
  wzDebug.flying:
    description: Toggle Flying Debug Mode
    usage: /wzDebug.flying [player]
    permission: wauz.system
  wzDebug.attack:
    description: Toggle Attack Debug Mode
    usage: /wzDebug.attack [player]
    permission: wauz.system
  wzDebug.defense:
    description: Toggle Defense Debug Mode
    usage: /wzDebug.defense [player]
    permission: wauz.system
  wzGetPet:
    description: Get Pet from String
    usage: /wzGetPet [petname] [player]
    permission: wauz.system
  wzGetEquip:
    description: Get Equip from String
    usage: /wzGetEquip [equipname] [tier] [player]
  wzGetEquip.enhanced:
    description: Get Enhanced Equip from String
    usage: /wzGetEquip.enhanced [enname] [enlvl] [player]
    permission: wauz.system
  wzGetRune:
    description: Get Rune from String
    usage: /wzGetRune [runename] [player]
    permission: wauz.system
  wzSkill:
    description: Execute Skill
    usage: /wzSkill [skillname]
    permission: wauz.system
  wzSkill.weapon:
    description: Get Weapon with Skillgem
    usage: /wzSkill.weapon [skillname]
    permission: wauz.system
permissions:
  wauz.system:
    description: Gives access to system commands.
    default: op
  wauz.normal:
    description: Permission assigned to new players.
    default: true
  wauz.debug:
    description: Shows the personalized debug log in chat.
    default: false
  wauz.debug.magic:
    description: Infinite mana and 1 second skill cooldowns.
    default: false
  wauz.debug.crafting:
    description: Unlock all recipes, craftable without cost.
    default: false
  wauz.debug.building:
    description: Enables building in all areas.
    default: false
  wauz.debug.flying:
    description: Allows to fly very fast in all modes.
    default: false
  wauz.debug.attack:
    description: Increases damage output drastically.
    default: false
  wauz.debug.defense:
    description: Reduces damage taken to zero.
    default: false