package eu.wauz.wauzcore.items.identifiers;

import java.util.List;
import java.util.Random;

import org.bukkit.Effect;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;

import eu.wauz.wauzcore.items.enums.Rarity;
import eu.wauz.wauzcore.items.enums.Tier;
import eu.wauz.wauzcore.items.runes.insertion.WauzRune;
import eu.wauz.wauzcore.items.runes.insertion.WauzRuneInserter;
import eu.wauz.wauzcore.system.util.Chance;

/**
 * Typed identifier, used for identifying rune items.
 * 
 * @author Wauzmons
 * 
 * @see WauzIdentifier
 */
public class WauzRuneIdentifier {
	
	/**
	 * A random instance, for rolling item stats and rarities.
	 */
	private Random random = new Random();
	
	/**
	 * Identifies the item, based on the given event.
	 * Additional methods are called to roll rarity and tier.
	 * Then a random rune type is taken and added to the item's display name.
	 * Finally the new name, item lores and flags will be generated by the builder.
	 * 
	 * @param player The player who identifies the item.
	 * @param runeItemStack The rune item stack, that is getting identified.
	 * 
	 * @see Rarity#getRandomRuneRarity()
	 * @see Tier#getRuneTier(String)
	 * @see WauzRuneBuilder#generate(Tier, Rarity)
	 */
	public void identifyRune(Player player, ItemStack runeItemStack) {
		String itemName = runeItemStack.getItemMeta().getDisplayName();
		Rarity rarity = Rarity.getRandomRuneRarity();
		Tier tier = Tier.getRuneTier(itemName);
		
		List<WauzRune> runes = WauzRuneInserter.getAllRunes();
		WauzRune rune = runes.get(random.nextInt(runes.size()));
		int mightStat = (int) ((2 + random.nextDouble() / 2) * tier.getMultiplier() * rarity.getMultiplier());
		
		WauzRuneBuilder builder = new WauzRuneBuilder(rune);
		builder.addMightStat(mightStat);
		builder.addSuccessStat(Chance.minMax(25 * rarity.getStarCount(), 10 * rarity.getStarCount() + 60));
		ItemStack generatedItemStack = builder.generate(tier, rarity);
		runeItemStack.setType(generatedItemStack.getType());
		runeItemStack.setItemMeta(generatedItemStack.getItemMeta());
		player.getWorld().playEffect(player.getLocation(), Effect.ANVIL_USE, 0);
	}

}
